# Generated by Django 5.1 on 2024-08-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="payment_method",
        ),
    ]
