# Generated by Django 5.1 on 2024-08-28 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_platform", "0004_course_pay_amount_course"),
        ("users", "0003_remove_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="pay_course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="learning_platform.course",
                verbose_name="оплаченный курс",
            ),
        ),
    ]
