# Generated by Django 5.1 on 2024-08-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_platform", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="описание"),
        ),
    ]
