# Generated by Django 5.1 on 2024-08-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_platform", "0003_answeroption_owner_test_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="pay_amount_course",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="стоимость курса",
            ),
        ),
    ]
