# Generated by Django 5.1 on 2024-08-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_platform", "0004_course_pay_amount_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="pay_amount_course",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="стоимость курса"
            ),
        ),
    ]
